homeassistant:
  whitelist_external_dirs:
    - /tmp

camera:
  - platform: mjpeg
    name: cam1
    mjpeg_url: !secret frigate_cam_url 
  - platform: local_file
    name: cam1_history1
    file_path: /tmp/cam1_image1.jpg    
  - platform: local_file
    name: cam1_history2
    file_path: /tmp/cam1_image2.jpg    
  - platform: local_file
    name: cam1_history3
    file_path: /tmp/cam1_image3.jpg    
  - platform: local_file
    name: cam1_history4
    file_path: /tmp/cam1_image4.jpg    
  - platform: local_file
    name: cam1_history5
    file_path: /tmp/cam1_image5.jpg

automation:

  alias: create_history 
  trigger:
  - entity_id: binary_sensor.cam1_person
    from: 'off'
    platform: state
    to: 'on'
  action:
  - data:
      entity_id: camera.cam1_history2
      filename: /tmp/cam1_image1.jpg
    service: camera.snapshot
  - data:
      entity_id: camera.cam1_history3
      filename: /tmp/cam1_image2.jpg
    service: camera.snapshot
  - data:
      entity_id: camera.cam1_history4 
      filename: /tmp/cam1_image3.jpg
    service: camera.snapshot
  - data:
      entity_id: camera.cam1_history5
      filename: /tmp/cam1_image4.jpg
    service: camera.snapshot
  - data:
      entity_id: camera.cam1         
      filename: /tmp/cam1_image5.jpg
    service: camera.snapshot
    
script:
  setup_frigate_history:
    sequence:
      - data:
          entity_id: camera.cam1         
          filename: /tmp/cam1_image5.jpg
        service: camera.snapshot
      - data:
          entity_id: camera.cam1         
          filename: /tmp/cam1_image4.jpg
        service: camera.snapshot
      - data:
          entity_id: camera.cam1         
          filename: /tmp/cam1_image3.jpg
        service: camera.snapshot
      - data:
          entity_id: camera.cam1         
          filename: /tmp/cam1_image2.jpg
        service: camera.snapshot
      - data:
          entity_id: camera.cam1         
          filename: /tmp/cam1_image1.jpg
        service: camera.snapshot
