homeassistant:
  whitelist_external_dirs:
    - /config/www

camera:
  - platform: mjpeg
    name: cam1
    mjpeg_url: !secret frigate_cam1_url 
  - platform: local_file
    name: cam1_history1
    file_path: /config/www/cam1_image1.jpg    
  - platform: local_file
    name: cam1_history2
    file_path: /config/www/cam1_image2.jpg    
  - platform: local_file
    name: cam1_history3
    file_path: /config/www/cam1_image3.jpg    
  - platform: local_file
    name: cam1_history4
    file_path: /config/www/cam1_image4.jpg    
  - platform: local_file
    name: cam1_history5
    file_path: /config/www/cam1_image5.jpg

automation:

  alias: create_cam1_history 
  trigger:
  - entity_id: binary_sensor.cam1_person
    from: 'off'
    platform: state
    to: 'on'
  action:
  action:
  - data:
      entity_id: automation.create_cam1_history
    service: automation.turn_off
  - data:
      entity_id: camera.cam1_history2
      filename: /config/www/cam1_image1.jpg
    service: camera.snapshot
  - data:
      entity_id: camera.cam1_history3
      filename: /config/www/cam1_image2.jpg
    service: camera.snapshot
  - data:
      entity_id: camera.cam1_history4 
      filename: /config/www/cam1_image3.jpg
    service: camera.snapshot
  - data:
      entity_id: camera.cam1_history5
      filename: /config/www/cam1_image4.jpg
    service: camera.snapshot
  - data:
      entity_id: camera.cam1         
      filename: /config/www/cam1_image5.jpg
    service: camera.snapshot
  - delay:
    seconds: 30
  - data:
      entity_id: automation.create_cam1_history
    service: automation.turn_on
